export const ITEM_SUGGESTIONS = [
  "Milk 🥛",
  "Heavy cream",
  "Cream",
  "Half-and-half",
  "Tomatoes 🍅",
  "Corn on the cob 🌽",
  "Blueberries",
  "Apples 🍏",
  "Oranges 🍊",
  "Lemons 🍋",
  "Bananas 🍌",
  "Watermelon 🍉",
  "Grapes 🍇",
  "Strawberries 🍓",
  "Cherries 🍒",
  "Peaches 🍑",
  "Mango 🥭",
  "Melon 🍈",
  "Pineapple 🍍",
  "Coconut 🥥",
  "Kiwis 🥝",
  "Eggplant 🍆",
  "Avocados 🥑",
  "Broccoli 🥦",
  "Kale 🥬",
  "Lettuce 🥬",
  "Cucumbers 🥒",
  "Zucchini 🥒",
  "Chilis 🌶",
  "Carrots 🥕",
  "Garlic 🧄",
  "Onions 🧅",
  "Potatoes 🥔",
  "Sweet potatoes 🍠",
  "Croissants 🥐",
  "Bagels 🥯",
  "Bread 🍞",
  "Baguette 🥖",
  "Pretzels 🥨",
  "Cheese 🧀",
  "Eggs 🥚",
  "Butter 🧈",
  "Spreadable butter 🧈",
  "Pancakes 🥞",
  "Pancake mix 🥞",
  "Waffles 🧇",
  "Waffle mix 🧇",
  "Bacon 🥓",
  "Steak 🥩",
  "Beef 🥩",
  "Chicken 🍗",
  "Wings 🍗",
  "Bone-in pork 🍖",
  "Hotdog buns 🌭",
  "Hotdogs 🌭",
  "Burger buns 🍔",
  "Pizza dough 🍕",
  "Frozen pizza 🍕",
  "Sandwich bread 🥪",
  "Sandwiches 🥪",
  "Salad 🥙",
  "Leafy salad 🥙",
  "Falafels 🧆",
  "Green salad 🥗",
  "Canned tomatoes 🥫",
  "Spaghetti 🍝",
  "Sushi 🍣",
  "Potstickers 🥟",
  "Dumplings 🥟",
  "Shrimps 🍤",
  "Ice cream 🍨",
  "Pie 🥧",
  "Shortcake 🍰",
  "Birthday cake 🎂",
  "Candy 🍭",
  "Treats 🍬",
  "Chocolate 🍫",
  "Dark chocolate 🍫",
  "Milk chocolate 🍫",
  "Popcorn 🍿",
  "Microwave popcorn 🍿",
  "Donuts 🍩",
  "Cookies 🍪",
  "Chocoloate cookies 🍪",
  "Peanuts 🥜",
  "Peanut butter 🥜",
  "Honey 🍯",
  "Baby formula 🍼",
  "Coffee ☕️",
  "Juiceboxes 🧃",
  "Soda 🥤",
  "Sake 🍶",
  "Beer 🍺",
  "Champagne 🍾",
  "Sparking wine 🥂",
  "Wine 🍷",
  "Gin 🍸",
  "Whiskey 🥃",
  "Rum 🍹",
  "Ice 🧊",
  "Salt 🧂",
  "Mayonnaise",
];

export const GROUP_SUGGESTIONS = [
  "Produce",
  "Bread",
  "Dairy",
  "Pasta",
  "Baking",
  "Deli",
  "Seafood",
  "Wine",
  "Meat",
  "Chips",
].sort();
