// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace PyroCssNamespace {
  export interface IPyroCss {
    after: string;
    bang: string;
    before: string;
    gravity: string;
    position: string;
    pyro: string;
  }
}

declare const PyroCssModule: PyroCssNamespace.IPyroCss;

export = PyroCssModule;
