// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    clearitems: string;
    click_to_edit: string;
    done_item: string;
    done_items: string;
    edit_groups_action: string;
    editaction: string;
    empty_list: string;
    item_description: string;
    list: string;
    list_item_edit_mode: string;
    listoptions: string;
    listoptions_section: string;
    loading_list_items: string;
    organize_groups: string;
    quantity_button: string;
    rainbow_animation: string;
    rainbow_text_animated: string;
    search_suggestions: string;
    sign_in_reminder: string;
    sorting_handle: string;
    suggestion_button: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
