// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    clearitems: string;
    done_item: string;
    done_items: string;
    editaction: string;
    empty_list: string;
    item_description: string;
    list: string;
    listoptions: string;
    listoptions_section: string;
    loading_list_items: string;
    rainbow_animation: string;
    rainbow_text_animated: string;
    search_suggestions: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
