// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    add_picked_words_container: string;
    debug_found_foodwords: string;
    list_pictures: string;
    picture_group: string;
    pictures: string;
    words: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
