// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    clearitems: string;
    list: string;
    listoptions: string;
    listoptions_section: string;
    menu_options_button: string;
    week: string;
    week_heading: string;
    weekday: string;
    weekday_past: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
