// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    add_new_menu: string;
    card: string;
    menu_owners: string;
    menu_preview: string;
    menu_preview_meals: string;
    menus: string;
    preview_meal: string;
    sign_in_reminder: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
