// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    add_new_group: string;
    file: string;
    list_preview_items: string;
    mappings: string;
    names: string;
    shopping: string;
    sources: string;
    sourcesContent: string;
    version: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
