// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    add_new_group: string;
    card: string;
    list_owners: string;
    list_preview: string;
    list_preview_items: string;
    shopping: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
