// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    file: string;
    mappings: string;
    names: string;
    offline_warning: string;
    sources: string;
    sourcesContent: string;
    version: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
