# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Display Node version
        run: node --version
      - name: Display Yarn version
        run: yarn --version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn --frozen-lockfile

      - name: Create a firebase config
        run: |
          # These are NOT secrets. It's public stuff.

          export PREACT_APP_FIREBASE_APIKEY=AIzaSyBfbOjXiFeMOBljhjZUxGSXHR5Ry0ienOs
          export PREACT_APP_FIREBASE_AUTHDOMAIN=thatsgroce.firebaseapp.com
          export PREACT_APP_FIREBASE_DATABASEURL=https://thatsgroce.firebaseio.com
          export PREACT_APP_FIREBASE_PROJECTID=thatsgroce
          export PREACT_APP_FIREBASE_STORAGEBUCKET=thatsgroce.appspot.com
          export PREACT_APP_FIREBASE_MESSAGINGSENDERID=190607180135
          export PREACT_APP_FIREBASE_APPID=1:190607180135:web:011ff0f368bd93b4cbefc2
          export PREACT_APP_FIREBASE_MEASUREMENTID=G-97FY43FWT4

      - name: Build
        run: ./bin/build
